/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Premium Emerald & Gold Solar Theme (High Contrast)
        background: "#f8fafc",
        "on-background": "#0f172a",
        "on-surface": "#0f172a",
        "on-surface-variant": "#334155",
        surface: "#ffffff",
        "surface-variant": "#f1f5f9",
        "surface-container": "#cbd5e1",
        "surface-container-low": "#f8fafc",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#ffffff",
        "surface-dim": "#e2e8f0",

        primary: "#047857",
        "on-primary": "#ffffff",
        "primary-container": "#10b981",
        "on-primary-container": "#022c22",
        "primary-fixed": "#a7f3d0",
        "primary-fixed-dim": "#6ee7b7",
        "on-primary-fixed": "#022c22",

        secondary: "#d97706",
        "on-secondary": "#ffffff",
        "secondary-container": "#f59e0b",
        "on-secondary-container": "#451a03",
        "secondary-fixed": "#fef3c7",
        "secondary-fixed-dim": "#fde68a",
        "on-secondary-fixed": "#451a03",
        "on-secondary-fixed-variant": "#78350f",

        tertiary: "#0284c7",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#38bdf8",
        "on-tertiary-container": "#0369a1",
        "tertiary-fixed": "#e0f2fe",
        "tertiary-fixed-dim": "#bae6fd",
        "on-tertiary-fixed": "#0c4a6e",
        "on-tertiary-fixed-variant": "#0369a1",

        error: "#dc2626",
        "on-error": "#ffffff",
        "error-container": "#fee2e2",
        "on-error-container": "#7f1d1d",

        outline: "#64748b",
        "outline-variant": "#cbd5e1",

        "inverse-surface": "#0f172a",
        "inverse-on-surface": "#f8fafc",
        "inverse-primary": "#34d399",
        "surface-tint": "#047857",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max-width": "1440px",
        "stack-sm": "8px",
        "margin-desktop": "32px",
        "stack-lg": "32px",
        gutter: "24px",
        unit: "4px",
        "stack-md": "16px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        headline: ["Hanken Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        technical: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "technical-mono": ["13px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
