'use client';

import { useState, useEffect, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import { DataTable } from '@/components/ui/data-table';
import { Button } from '@/components/ui/button';
import { Modal } from '@/components/ui/modal';
import { Input } from '@/components/ui/input';
import { SolarQuotationTemplate, SolarQuotationData } from '@/components/quotations/solar-quotation-template';

interface Quotation {
  id: number;
  quotation_number: string;
  project_id: number;
  customer_name: string;
  quotation_date: string;
  valid_until?: string;
  system_type?: string;
  capacity_kw?: number;
  total_amount: number;
  status: string;
  subtotal?: number;
  discount_amount?: number;
  discount_percentage?: number;
  gst_amount?: number;
  gst_percentage?: number;
  items?: any[];
  terms_conditions?: string;
  remarks?: string;
  created_by_name?: string;
}

function QuotationsPageContent() {
  const [quotations, setQuotations] = useState<Quotation[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [selectedQuotation, setSelectedQuotation] = useState<Quotation | null>(null);
  const [isDetailsOpen, setIsDetailsOpen] = useState(false);
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [isOcrModalOpen, setIsOcrModalOpen] = useState(false);
  const searchParams = useSearchParams();
  const initialProjectId = searchParams.get('project_id') || '';

  useEffect(() => { fetchQuotations(); }, []);

  const fetchQuotations = async () => {
    try {
      setIsLoading(true);
      const response = await fetch('/api/quotations');
      const data = await response.json();
      if (Array.isArray(data)) setQuotations(data);
      else setQuotations([]);
    } catch { setQuotations([]); } finally { setIsLoading(false); }
  };

  const handleViewDetails = async (row: Quotation) => {
    try {
      const res = await fetch(`/api/quotations/${row.id}`);
      const data = await res.json();
      setSelectedQuotation(data || row);
    } catch { setSelectedQuotation(row); }
    setIsDetailsOpen(true);
  };

  const handleUpdateStatus = async (id: number, status: string) => {
    try {
      await fetch(`/api/quotations/${id}`, {
        method: 'PUT', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status }),
      });
      await fetchQuotations();
      setIsDetailsOpen(false);
    } catch (e) { console.error(e); }
  };

  const formatCurrency = (amount: number) =>
    new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', minimumFractionDigits: 0 }).format(amount);

  const statusColors: Record<string, string> = {
    ACCEPTED: 'bg-tertiary-container text-on-tertiary-container',
    SENT: 'bg-secondary-container text-on-secondary-container',
    DRAFT: 'bg-primary-fixed text-on-primary-fixed',
    REJECTED: 'bg-error-container text-on-error-container',
    EXPIRED: 'bg-error-container text-on-error-container',
  };

  const columns = [
    { key: 'quotation_number', title: 'Quotation #', render: (v: string) => <span className="font-technical-mono text-sm font-medium">{v}</span> },
    {
      key: 'customer_name', title: 'Customer',
      render: (v: string, row: Quotation) => (
        <div>
          <div className="font-medium text-on-surface">{v}</div>
          <div className="text-xs text-on-surface-variant">ES-2026-{String(row.project_id).padStart(4, '0')}</div>
        </div>
      ),
    },
    {
      key: 'system_details', title: 'System',
      render: (_: any, row: Quotation) => (
        <span className="text-sm text-on-surface">{row.capacity_kw ? `${row.capacity_kw} kW` : '-'} {row.system_type?.replace(/_/g, ' ')}</span>
      ),
    },
    { key: 'quotation_date', title: 'Date', render: (v: string) => new Date(v).toLocaleDateString() },
    { key: 'valid_until', title: 'Valid Until', render: (v?: string) => v ? new Date(v).toLocaleDateString() : '-' },
    {
      key: 'total_amount', title: 'Amount',
      render: (v: number) => <span className="font-medium font-technical-mono">{formatCurrency(v)}</span>,
    },
    {
      key: 'created_by_name',
      title: 'Generated By',
      render: (v?: string) => (
        <span className="text-xs font-medium text-slate-700 dark:text-slate-300">
          👤 {v || 'System'}
        </span>
      ),
    },
    {
      key: 'status', title: 'Status',
      render: (v: string) => <span className={`status-badge ${statusColors[v] || 'bg-surface-container text-on-surface-variant'}`}>{v}</span>,
    },
    {
      key: 'actions', title: 'Actions',
      render: (_: any, row: Quotation) => (
        <div className="flex items-center gap-2">
          <button onClick={() => handleViewDetails(row)} className="p-1 hover:bg-surface-container-low rounded" title="View & Print">
            <span className="material-symbols-outlined text-sm text-on-surface-variant">visibility</span>
          </button>
          {row.status === 'DRAFT' && (
            <button onClick={() => handleUpdateStatus(row.id, 'SENT')} className="p-1 hover:bg-surface-container-low rounded" title="Send">
              <span className="material-symbols-outlined text-sm text-secondary">send</span>
            </button>
          )}
          {row.status === 'SENT' && (
            <>
              <button onClick={() => handleUpdateStatus(row.id, 'ACCEPTED')} className="p-1 hover:bg-tertiary-container rounded" title="Accept">
                <span className="material-symbols-outlined text-sm text-tertiary">check</span>
              </button>
              <button onClick={() => handleUpdateStatus(row.id, 'REJECTED')} className="p-1 hover:bg-error-container rounded" title="Reject">
                <span className="material-symbols-outlined text-sm text-error">close</span>
              </button>
            </>
          )}
        </div>
      ),
    },
  ];

  return (
    <div className="space-y-8">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-headline-md font-bold text-on-surface">Quotations</h1>
          <p className="text-body-md text-on-surface-variant mt-1">Manage solar system quotations — Excellent Solar official pattern</p>
        </div>
        <Button onClick={() => setIsCreateOpen(true)} className="btn-primary flex items-center gap-2">
          <span className="material-symbols-outlined">description</span>
          New Quotation
        </Button>
      </div>

      <Modal isOpen={isOcrModalOpen} onClose={() => setIsOcrModalOpen(false)} title="Import Quotation PDF" size="lg">
        <OcrQuotationImportModal onClose={() => setIsOcrModalOpen(false)} onSuccess={() => { setIsOcrModalOpen(false); fetchQuotations(); }} />
      </Modal>

      <div className="card-base overflow-hidden">
        <DataTable columns={columns} data={quotations} isLoading={isLoading} emptyMessage="No quotations found. Create your first quotation." />
      </div>

      <Modal isOpen={isDetailsOpen} onClose={() => setIsDetailsOpen(false)} title={`Quotation ${selectedQuotation?.quotation_number}`} size="5xl">
        {selectedQuotation && (
          <QuotationDetails quotation={selectedQuotation} onClose={() => setIsDetailsOpen(false)} onUpdateStatus={handleUpdateStatus} />
        )}
      </Modal>

      <Modal isOpen={isCreateOpen} onClose={() => setIsCreateOpen(false)} title="Create Quotation" size="5xl">
        <CreateQuotationForm
          initialProjectId={initialProjectId}
          onSuccess={() => { setIsCreateOpen(false); fetchQuotations(); }}
          onCancel={() => setIsCreateOpen(false)}
        />
      </Modal>
    </div>
  );
}

export default function QuotationsPage() {
  return (
    <Suspense fallback={<div className="p-8 text-center animate-pulse">Loading quotations...</div>}>
      <QuotationsPageContent />
    </Suspense>
  );
}

// ─── QuotationDetails: renders Excellent Solar PDF template ───
function QuotationDetails({ quotation, onClose, onUpdateStatus }: any) {
  const items = Array.isArray(quotation.items) ? quotation.items : [];

  const materials = items && items.length > 0
    ? items.map((item: any, idx: number) => ({
        sr_no: idx + 1,
        material: (item.description || item.product_name || item.material || '').toUpperCase(),
        quantity: String(item.quantity || '1'),
        brand: item.brand || item.product_code || 'N.A',
        description: item.unit || item.remarks || item.description_text || '',
      }))
    : undefined;

  const capacityKw = Number(quotation.capacity_kw || 0);
  const totalAmount = Number(quotation.total_amount || 0);
  const ratePerWatt = quotation.rate_per_watt || (capacityKw > 0 && totalAmount > 0 ? (totalAmount / (capacityKw * 1000)).toFixed(2) : '23.50');

  const terms = quotation.terms_conditions
    ? quotation.terms_conditions.split('\n').filter(Boolean)
    : undefined;

  const solarData: Partial<SolarQuotationData> = {
    customer_name: quotation.customer_name || '',
    date: quotation.quotation_date ? new Date(quotation.quotation_date).toLocaleDateString('en-IN') : '',
    project_type: (quotation.system_type || 'ONGRID_SOLAR').replace(/_/g, ' '),
    capacity: capacityKw ? `${capacityKw} KW` : '',
    location: quotation.remarks || '',
    materials,
    rate_per_watt: String(ratePerWatt),
    total_cost: totalAmount > 0 ? totalAmount.toLocaleString('en-IN') : '47,00,000',
    gst_info: quotation.gst_percentage ? `GST EXTRA (${quotation.gst_percentage}%)` : 'GST EXTRA (8.9%)',
    terms,
    latitude: quotation.project_latitude,
    longitude: quotation.project_longitude,
  };

  return (
    <div className="space-y-4 max-h-[85vh] overflow-y-auto pr-1 print:max-h-none print:overflow-visible">
      <div className="flex items-center justify-between print:hidden gap-2 pb-3 border-b border-outline-variant">
        <span className={`text-xs px-3 py-1 rounded-full font-bold ${
          quotation.status === 'ACCEPTED' ? 'bg-green-100 text-green-800' :
          quotation.status === 'SENT' ? 'bg-blue-100 text-blue-800' :
          quotation.status === 'REJECTED' ? 'bg-red-100 text-red-800' : 'bg-yellow-100 text-yellow-800'
        }`}>{quotation.status}</span>
        <div className="flex gap-2">
          {quotation.status === 'DRAFT' && (
            <Button size="sm" onClick={() => onUpdateStatus(quotation.id, 'SENT')} className="bg-blue-600 text-white">Mark as Sent</Button>
          )}
          {quotation.status === 'SENT' && (
            <>
              <Button size="sm" onClick={() => onUpdateStatus(quotation.id, 'ACCEPTED')} className="bg-green-600 text-white">Accept</Button>
              <Button size="sm" onClick={() => onUpdateStatus(quotation.id, 'REJECTED')} className="bg-red-600 text-white">Reject</Button>
            </>
          )}
          <Button size="sm" onClick={() => window.print()} className="flex items-center gap-1 bg-slate-800 text-white">
            <span className="material-symbols-outlined text-sm">print</span> Download PDF
          </Button>
          <Button size="sm" variant="outline" onClick={onClose}>Close</Button>
        </div>
      </div>
      <div className="border rounded overflow-x-auto bg-white print-only">
        <SolarQuotationTemplate data={solarData} />
      </div>
    </div>
  );
}

// ─── SearchableProductSelect ───
function SearchableProductSelect({ products, onSelect }: { products: any[]; onSelect: (prodId: string) => void }) {
  const [searchTerm, setSearchTerm] = useState('');
  const [isOpen, setIsOpen] = useState(false);

  const productList = Array.isArray(products) ? products : [];
  const filtered = productList.filter(p => {
    if (!searchTerm.trim()) return true;
    const term = searchTerm.toLowerCase();
    return (
      (p.name && String(p.name).toLowerCase().includes(term)) ||
      (p.product_code && String(p.product_code).toLowerCase().includes(term)) ||
      (p.brand && String(p.brand).toLowerCase().includes(term)) ||
      (p.category && String(p.category).toLowerCase().includes(term)) ||
      (p.specification && String(p.specification).toLowerCase().includes(term))
    );
  });

  return (
    <div className="relative w-full">
      <input
        type="text"
        value={searchTerm}
        onChange={e => { setSearchTerm(e.target.value); setIsOpen(true); }}
        onFocus={() => setIsOpen(true)}
        onBlur={() => setTimeout(() => setIsOpen(false), 200)}
        placeholder="🔍 Type keywords to search inventory..."
        className="w-full text-sm font-semibold border-2 border-amber-400 focus:border-amber-600 rounded px-2.5 py-1.5 bg-amber-50 text-slate-900 placeholder:text-slate-500 shadow-sm"
      />
      {searchTerm && (
        <button
          type="button"
          onClick={() => { setSearchTerm(''); setIsOpen(true); }}
          className="absolute right-2.5 top-2 font-black text-slate-400 hover:text-slate-700 text-sm z-10"
        >
          ✕
        </button>
      )}

      {isOpen && (
        <div className="absolute left-0 right-0 top-full mt-1 z-30 max-h-56 overflow-y-auto bg-white border-2 border-slate-400 rounded-md shadow-2xl divide-y divide-slate-100 text-sm">
          {filtered.length === 0 ? (
            <div className="p-3 text-xs text-slate-500 text-center font-medium">❌ No matching stock products</div>
          ) : (
            filtered.map(p => (
              <div
                key={p.id}
                onMouseDown={(e) => {
                  e.preventDefault();
                  onSelect(String(p.id));
                  setSearchTerm('');
                  setIsOpen(false);
                }}
                className="w-full text-left p-2.5 hover:bg-amber-100 transition-colors flex flex-col gap-0.5 cursor-pointer text-slate-900"
              >
                <div className="font-bold text-sm text-slate-900 flex justify-between items-center">
                  <span>{p.name}</span>
                  <span className="text-xs px-2 py-0.5 bg-slate-200 text-slate-700 rounded font-mono font-bold">{p.product_code}</span>
                </div>
                <div className="text-xs text-slate-600 flex flex-wrap gap-2 mt-0.5">
                  {p.brand && <span className="font-bold text-amber-700">Brand: {p.brand}</span>}
                  {p.category && <span className="text-slate-500">Category: {p.category}</span>}
                  {p.specification && <span className="italic text-slate-500">{p.specification}</span>}
                </div>
              </div>
            ))
          )}
        </div>
      )}
    </div>
  );
}

// ─── CreateQuotationForm ───
interface LineItem {
  description: string;
  quantity: string;
  brand: string;
  unit: string; // Description column
  sort_order: number;
}

function CreateQuotationForm({ onSuccess, onCancel, initialProjectId = '' }: any) {
  const [step, setStep] = useState<'select' | 'template' | 'custom'>('select');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');
  const [projectId, setProjectId] = useState(initialProjectId);
  const [quotationDate, setQuotationDate] = useState(new Date().toISOString().split('T')[0]);
  const [validUntil, setValidUntil] = useState('');
  const [gstPct, setGstPct] = useState(8.9);
  const [ratePerWatt, setRatePerWatt] = useState('23.50');
  const [totalCostOverride, setTotalCostOverride] = useState('');
  const [systemType, setSystemType] = useState('ONGRID_SOLAR');
  const [capacityKw, setCapacityKw] = useState('200');
  const [location, setLocation] = useState('JALALABAD');
  const [termsConditions, setTermsConditions] = useState(
    '1. Validity: This quotation is valid for 15 days from the date of issue.\n2. Payment Terms: 30% advance, 65% on delivery, 5% on completion\n3. Maintenance: 1 Year , Maintenance (without panel washing) included, Annual Maintenance Contract available after 1 year optional'
  );
  const [templateId, setTemplateId] = useState('');
  const [templates, setTemplates] = useState<any[]>([]);
  const [inventoryProducts, setInventoryProducts] = useState<any[]>([]);
  const [templatePreview, setTemplatePreview] = useState<any | null>(null);
  
  const [items, setItems] = useState<LineItem[]>([
    { description: 'SOLAR PANELS', quantity: '0', brand: 'WAAREE TOPCON', unit: '615 W', sort_order: 1 },
    { description: 'INVERTER', quantity: '0', brand: 'WAAREE/LUMINOUS', unit: '8 YEARS WARRANTY', sort_order: 2 },
    { description: 'EARTHING', quantity: '0', brand: '3 METER', unit: 'COPPER BONDED WITH CHEMICAL', sort_order: 3 },
    { description: 'LIGTNING ARRESTER', quantity: '0', brand: '1 METER', unit: 'COPPER BONDED', sort_order: 4 },
    { description: 'STRUCTURE', quantity: '0', brand: '70 MM HEIGHT', unit: 'ALUMINIUM', sort_order: 5 },
    { description: 'EARTHING WIRE', quantity: '0', brand: 'HAVELLS', unit: '4 MM & 6MM', sort_order: 6 },
    { description: 'SERVICE WIRE', quantity: '0', brand: 'AS PER PSPCL', unit: '150 MM ALUMINIUM', sort_order: 7 },
    { description: 'DC WIRE', quantity: '0', brand: 'WAAREE/HAVELLS', unit: '6 MM', sort_order: 8 },
    { description: 'ACDB', quantity: '0', brand: 'HAVELLS', unit: '', sort_order: 9 },
    { description: 'DCDB', quantity: '0', brand: 'N.A', unit: '', sort_order: 10 },
  ]);
  const [projects, setProjects] = useState<any[]>([]);

  useEffect(() => {
    fetch('/api/system-templates').then(r => r.json()).then(d => { if (Array.isArray(d)) setTemplates(d); }).catch(() => {});
    fetch('/api/projects?limit=1000').then(r => r.json()).then(d => { if (d?.projects) setProjects(d.projects); }).catch(() => {});
    fetch('/api/inventory/products').then(r => r.json()).then(d => {
      if (d?.products) setInventoryProducts(d.products);
      else if (Array.isArray(d)) setInventoryProducts(d);
    }).catch(() => {});
  }, []);

  useEffect(() => {
    if (templateId) {
      fetch(`/api/system-templates/${templateId}`).then(r => r.json()).then(d => setTemplatePreview(d)).catch(() => {});
    } else setTemplatePreview(null);
  }, [templateId]);

  const addItem = () => setItems(prev => [
    ...prev, { description: '', quantity: '0', brand: '', unit: '', sort_order: prev.length + 1 },
  ]);

  const removeItem = (idx: number) => setItems(prev => prev.filter((_, i) => i !== idx));

  const updateItem = (idx: number, field: keyof LineItem, value: any) => {
    setItems(prev => prev.map((item, i) => {
      if (i !== idx) return item;
      return { ...item, [field]: value };
    }));
  };

  const handleSelectInventoryProduct = (idx: number, productIdStr: string) => {
    if (!productIdStr) return;
    const prod = inventoryProducts.find(p => p.id === Number(productIdStr));
    if (prod) {
      updateItem(idx, 'description', prod.name || prod.product_code);
      updateItem(idx, 'brand', prod.brand || prod.category || prod.product_code || 'EXCELLENT');
      updateItem(idx, 'unit', prod.specification || prod.model || prod.unit || '');
    }
  };

  const calculatedTotal = capacityKw && ratePerWatt ? Math.round(Number(capacityKw) * 1000 * Number(ratePerWatt)) : 4700000;
  const finalTotalAmount = totalCostOverride ? Number(totalCostOverride) : calculatedTotal;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!projectId) { setError('Please select a project.'); return; }
    setError('');
    setSubmitting(true);
    try {
      const payload: any = {
        project_id: Number(projectId),
        quotation_date: quotationDate,
        valid_until: validUntil || undefined,
        gst_percentage: gstPct,
        system_type: systemType,
        capacity_kw: capacityKw ? Number(capacityKw) : null,
        rate_per_watt: ratePerWatt,
        terms_conditions: termsConditions,
        remarks: location,
        status: 'DRAFT',
      };

      if (step === 'template' && templateId) {
        payload.system_template_id = Number(templateId);
      } else {
        payload.items = items.map((item, i) => ({
          description: item.description,
          quantity: item.quantity,
          brand: item.brand,
          unit: item.unit,
          unit_price: 0,
          line_total: 0,
          discount_amount: 0, tax_amount: 0, sort_order: i + 1,
        }));
        payload.subtotal = finalTotalAmount;
        payload.discount_amount = 0;
        payload.gst_amount = Math.round(finalTotalAmount * (gstPct / 100));
        payload.total_amount = finalTotalAmount;
      }

      const res = await fetch('/api/quotations', {
        method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || `HTTP ${res.status}`);
      onSuccess();
    } catch (err: any) {
      setError(err.message || 'Failed to create quotation');
    } finally { setSubmitting(false); }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4 max-h-[80vh] overflow-y-auto pr-1">
      {error && <div className="p-3 bg-red-50 text-red-700 border border-red-200 rounded text-sm">{error}</div>}

      {step === 'select' && (
        <div className="space-y-4">
          <p className="text-on-surface-variant font-medium">How would you like to create the solar quotation?</p>
          <div className="grid grid-cols-2 gap-4">
            {[
              { label: 'From System Template', icon: 'description', desc: 'Use pre-configured system templates', s: 'template' as const },
              { label: 'Custom Solar Quotation', icon: 'edit_note', desc: 'Build custom quote with inventory items & 5-column table', s: 'custom' as const },
            ].map(opt => (
              <button key={opt.s} type="button" onClick={() => setStep(opt.s)}
                className="p-4 border-2 border-outline-variant rounded-lg hover:border-primary-container transition-colors text-left bg-surface-container-lowest">
                <div className="font-bold text-on-surface mb-1 flex items-center gap-2 text-base">
                  <span className="material-symbols-outlined text-primary-container text-xl">{opt.icon}</span>{opt.label}
                </div>
                <div className="text-xs text-on-surface-variant">{opt.desc}</div>
              </button>
            ))}
          </div>
        </div>
      )}

      {(step === 'template' || step === 'custom') && (
        <>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-label-bold text-on-surface mb-1">Select Customer Project *</label>
              <select 
                value={projectId} 
                onChange={e => {
                  const pid = e.target.value;
                  setProjectId(pid);
                  if (pid) {
                    const p = projects.find(proj => proj.id === Number(pid));
                    if (p) {
                      const fullAddress = [p.customer_address, p.customer_city, p.customer_district]
                        .filter(Boolean)
                        .join(', ');
                      setLocation(fullAddress || 'N/A');
                    }
                  }
                }} 
                className="input-base cursor-pointer font-medium text-sm" required>
                <option value="">Select a Project...</option>
                {projects.map(p => <option key={p.id} value={p.id}>{p.id_str} - {p.customer_name}</option>)}
              </select>
            </div>
            <div>
              <label className="block text-label-bold text-on-surface mb-1">Quotation Date *</label>
              <input type="date" value={quotationDate} onChange={e => setQuotationDate(e.target.value)} className="input-base text-sm" required />
            </div>
          </div>

          <div className="grid grid-cols-3 gap-3">
            <div>
              <label className="block text-label-bold text-on-surface mb-1">Valid Until</label>
              <input type="date" value={validUntil} onChange={e => setValidUntil(e.target.value)} className="input-base text-sm" />
            </div>
            <div>
              <label className="block text-label-bold text-on-surface mb-1">Project Type</label>
              <select value={systemType} onChange={e => setSystemType(e.target.value)} className="input-base cursor-pointer font-bold text-sm">
                <option value="ONGRID_SOLAR">ONGRID SOLAR</option>
                <option value="OFFGRID_SOLAR">OFFGRID SOLAR</option>
                <option value="HYBRID_SOLAR">HYBRID SOLAR</option>
              </select>
            </div>
            <div>
              <label className="block text-label-bold text-on-surface mb-1">Proposed Capacity (kW)</label>
              <input type="text" value={capacityKw} onChange={e => setCapacityKw(e.target.value)} className="input-base font-bold text-sm" placeholder="e.g. 200" />
            </div>
          </div>

          <div>
            <label className="block text-label-bold text-on-surface mb-1">Location / City</label>
            <input type="text" value={location} onChange={e => setLocation(e.target.value)} className="input-base uppercase font-bold text-sm" placeholder="e.g. JALALABAD" />
          </div>

          {step === 'template' && (
            <div>
              <label className="block text-label-bold text-on-surface mb-1">System Template *</label>
              <select value={templateId} onChange={e => setTemplateId(e.target.value)} className="input-base cursor-pointer text-sm" required>
                <option value="">Select a template...</option>
                {templates.map(t => <option key={t.id} value={t.id}>{t.name} ({t.capacity_kw} kW - {t.system_type})</option>)}
              </select>
            </div>
          )}

          {step === 'custom' && (
            <div>
              <div className="flex items-center justify-between mb-2">
                <div>
                  <label className="block text-label-bold text-on-surface">Material Details Table (5 Columns - Searchable Inventory Stock)</label>
                  <p className="text-xs text-slate-500">Pick from searchable stock inventory or edit material name, quantity, brand & description.</p>
                </div>
                <button type="button" onClick={addItem}
                  className="text-xs bg-slate-800 text-white font-bold px-3 py-1.5 rounded hover:bg-slate-900 transition-colors">
                  + Add Material Row
                </button>
              </div>

              <div className="overflow-x-auto border border-outline-variant rounded">
                <table className="w-full text-sm border-collapse">
                  <thead className="bg-[#6b9e38] text-black font-extrabold uppercase text-center border-b">
                    <tr>
                      <th className="p-2 w-8">#</th>
                      <th className="p-2 text-left w-[38%]">MATERIAL DETAIL</th>
                      <th className="p-2 text-center w-[16%]">QUANTITY</th>
                      <th className="p-2 text-center w-[18%]">BRAND</th>
                      <th className="p-2 text-center w-[20%]">Description</th>
                      <th className="p-2 w-8"></th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-outline-variant">
                    {items.map((item, idx) => (
                      <tr key={idx} className={idx % 2 === 0 ? 'bg-[#ffffe0]' : 'bg-white'}>
                        <td className="p-1.5 text-center font-bold text-slate-700 text-sm">{idx + 1}</td>
                        <td className="p-1.5 space-y-1.5">
                          <input
                            type="text"
                            value={item.description}
                            onChange={e => updateItem(idx, 'description', e.target.value)}
                            className="w-full border border-slate-300 rounded px-2.5 py-1.5 text-sm font-extrabold uppercase text-slate-900 bg-white"
                            placeholder="e.g. SOLAR PANELS"
                          />
                          {inventoryProducts.length > 0 && (
                            <SearchableProductSelect
                              products={inventoryProducts}
                              onSelect={prodId => handleSelectInventoryProduct(idx, prodId)}
                            />
                          )}
                        </td>
                        <td className="p-1.5">
                          <input
                            type="text"
                            value={item.quantity}
                            onChange={e => updateItem(idx, 'quantity', e.target.value)}
                            className="w-full border border-slate-300 rounded px-2 py-1.5 text-sm text-center font-black uppercase text-slate-900"
                            placeholder="e.g. 325 or 5+1"
                          />
                        </td>
                        <td className="p-1.5">
                          <input
                            type="text"
                            value={item.brand}
                            onChange={e => updateItem(idx, 'brand', e.target.value)}
                            className="w-full border border-slate-300 rounded px-2 py-1.5 text-sm text-center font-bold uppercase text-slate-900"
                            placeholder="e.g. WAAREE TOPCON"
                          />
                        </td>
                        <td className="p-1.5">
                          <input
                            type="text"
                            value={item.unit}
                            onChange={e => updateItem(idx, 'unit', e.target.value)}
                            className="w-full border border-slate-300 rounded px-2 py-1.5 text-sm text-center font-bold uppercase text-slate-900"
                            placeholder="e.g. 615 W"
                          />
                        </td>
                        <td className="p-1.5 text-center">
                          <button type="button" onClick={() => removeItem(idx)} className="text-red-500 hover:text-red-700 text-lg font-bold">✕</button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Commercial Summary Rate & Total Cost Box */}
              <div className="bg-[#d84315] text-white p-3 rounded-lg border border-black space-y-2 mt-4">
                <div className="font-extrabold text-xs uppercase tracking-wider text-amber-200 border-b border-amber-300/30 pb-1">
                  Commercial Pricing & GST Details (Official Quotation Summary)
                </div>
                <div className="grid grid-cols-3 gap-3 text-xs">
                  <div>
                    <label className="block text-[11px] font-bold mb-1 text-white">Rate / Watt (INR ₹)</label>
                    <input
                      type="text"
                      value={ratePerWatt}
                      onChange={e => setRatePerWatt(e.target.value)}
                      className="w-full p-1.5 border rounded text-slate-900 font-extrabold text-sm"
                      placeholder="23.50"
                    />
                  </div>
                  <div>
                    <label className="block text-[11px] font-bold mb-1 text-white">GST Extra %</label>
                    <input
                      type="number"
                      value={gstPct}
                      onChange={e => setGstPct(Number(e.target.value))}
                      className="w-full p-1.5 border rounded text-slate-900 font-extrabold text-sm"
                      placeholder="8.9"
                      step="0.1"
                    />
                  </div>
                  <div>
                    <label className="block text-[11px] font-bold mb-1 text-white">Total Project Cost (INR ₹)</label>
                    <input
                      type="number"
                      value={totalCostOverride || finalTotalAmount}
                      onChange={e => setTotalCostOverride(e.target.value)}
                      className="w-full p-1.5 border rounded text-slate-900 font-black text-base bg-amber-100"
                      placeholder="4700000"
                    />
                  </div>
                </div>
              </div>
            </div>
          )}

          <div>
            <label className="block text-label-bold text-on-surface mb-1">Terms & Conditions</label>
            <textarea value={termsConditions} onChange={e => setTermsConditions(e.target.value)} rows={3} className="input-base text-xs font-medium" />
          </div>
        </>
      )}

      <div className="flex justify-between pt-4 border-t border-outline-variant">
        {step !== 'select' && (
          <button type="button" onClick={() => setStep('select')}
            className="px-4 py-2 text-label-bold text-on-surface hover:bg-surface-container-low rounded transition-colors">
            ← Back
          </button>
        )}
        <div className="flex gap-3 ml-auto">
          <button type="button" onClick={onCancel} className="px-4 py-2 text-label-bold text-on-surface hover:bg-surface-container-low rounded transition-colors">Cancel</button>
          {step !== 'select' && (
            <button type="submit" className="btn-primary" disabled={submitting}>
              {submitting ? 'Creating...' : 'Create Solar Quotation'}
            </button>
          )}
        </div>
      </div>
    </form>
  );
}

function OcrQuotationImportModal({ onClose }: { onClose: () => void; onSuccess: () => void }) {
  const [filePath, setFilePath] = useState('');
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [loading, setLoading] = useState(false);
  const [quotationData, setQuotationData] = useState<SolarQuotationData | null>(null);
  const [viewMode, setViewMode] = useState<'preview' | 'json'>('preview');

  const handleParse = async () => {
    try {
      setLoading(true);
      let response: Response;
      if (selectedFile) {
        const formData = new FormData();
        formData.append('file', selectedFile);
        response = await fetch('/api/ocr/parse-pdf', { method: 'POST', body: formData });
      } else {
        response = await fetch('/api/ocr/parse-pdf', {
          method: 'POST', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ filePath }),
        });
      }
      const data = await response.json();
      if (!response.ok || data.error) throw new Error(data.error || 'Failed to parse PDF');
      setQuotationData(data);
    } catch (err: any) {
      alert(err.message || 'Error executing OCR');
    } finally { setLoading(false); }
  };

  return (
    <div className="space-y-4 max-h-[80vh] overflow-y-auto pr-1">
      <div className="bg-slate-50 dark:bg-slate-800 p-4 rounded-lg border space-y-3">
        <label className="block text-sm font-semibold">Upload Quotation PDF or specify File Path</label>
        <div className="flex gap-2">
          <Input type="file" accept=".pdf" onChange={e => { if (e.target.files?.[0]) setSelectedFile(e.target.files[0]); }} className="flex-1" />
          <Button onClick={handleParse} disabled={loading} className="bg-amber-600 hover:bg-amber-700 text-white">
            {loading ? 'Running OCR...' : 'Run OCR'}
          </Button>
        </div>
        <div className="text-xs text-slate-500">Or enter local file path:</div>
        <Input value={filePath} onChange={e => setFilePath(e.target.value)} placeholder="/path/to/quotation.pdf" className="text-xs font-mono" />
      </div>

      {quotationData && (
        <div className="space-y-4">
          <div className="flex items-center justify-between bg-amber-50 border border-amber-200 p-3 rounded-lg">
            <div>
              <span className="font-bold text-amber-900 block text-sm">✓ PDF OCR Parsed</span>
              <span className="text-xs text-amber-700">Customer: {quotationData.customer_name} | {quotationData.capacity}</span>
            </div>
            <div className="flex gap-2">
              <Button variant={viewMode === 'preview' ? 'default' : 'outline'} size="sm" onClick={() => setViewMode('preview')}>Pattern Preview</Button>
              <Button variant={viewMode === 'json' ? 'default' : 'outline'} size="sm" onClick={() => setViewMode('json')}>JSON Data</Button>
              <Button size="sm" onClick={() => window.print()} className="bg-blue-600 text-white">Print PDF</Button>
            </div>
          </div>
          {viewMode === 'preview' ? (
            <div className="border rounded-lg p-2 bg-slate-100 overflow-x-auto"><SolarQuotationTemplate data={quotationData} /></div>
          ) : (
            <pre className="bg-slate-900 text-green-400 p-4 rounded-lg text-xs font-mono max-h-96 overflow-y-auto">{JSON.stringify(quotationData, null, 2)}</pre>
          )}
        </div>
      )}
      <div className="flex justify-end gap-2 pt-2 border-t">
        <Button variant="outline" onClick={onClose}>Close</Button>
      </div>
    </div>
  );
}
